MediaManager/MediaManager.Web/Controllers/LibraryManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using MediaManager.Web.Models;

namespace MediaManager.Web.Controllers
{
    
    public class LibraryManagerController : Controller
    {
        MediaManagerEntities Db = new MediaManagerEntities();

        public ActionResult Index()
        {

            return View(Db.Movies);
        }

        public ActionResult Create()
        {
            ViewBag.MPAARatingId = new SelectList(Db.MPAARatings, "MPAARatingId", "Rating");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Movie myMovie)
        {
            if (ModelState.IsValid)
            {
                Db.Entry(myMovie).State = EntityState.Added;
                Db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MPAARatingId = new SelectList(Db.MPAARatings, "MPAARatingId", "Rating");
            return View(myMovie);
        }
    }
}

MediaManager/MediaManager.Web/Controllers/MPAARatingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MediaManager.Web.Models;

namespace MediaManager.Web.Controllers
{
    public class MPAARatingsController : Controller
    {
        private MediaManagerEntities db = new MediaManagerEntities();

        // GET: MPAARatings
        public ActionResult Index()
        {
            return View(db.MPAARatings.ToList());
        }

        // GET: MPAARatings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MPAARating mPAARating = db.MPAARatings.Find(id);
            if (mPAARating == null)
            {
                return HttpNotFound();
            }
            return View(mPAARating);
        }

        // GET: MPAARatings/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MPAARatings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MPAARatingId,Rating")] MPAARating mPAARating)
        {
            if (ModelState.IsValid)
            {
                db.MPAARatings.Add(mPAARating);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mPAARating);
        }

        // GET: MPAARatings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MPAARating mPAARating = db.MPAARatings.Find(id);
            if (mPAARating == null)
            {
                return HttpNotFound();
            }
            return View(mPAARating);
        }

        // POST: MPAARatings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MPAARatingId,Rating")] MPAARating mPAARating)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mPAARating).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mPAARating);
        }

        // GET: MPAARatings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MPAARating mPAARating = db.MPAARatings.Find(id);
            if (mPAARating == null)
            {
                return HttpNotFound();
            }
            return View(mPAARating);
        }

        // POST: MPAARatings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MPAARating mPAARating = db.MPAARatings.Find(id);
            db.MPAARatings.Remove(mPAARating);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MediaManager/MediaManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Media Manager", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Library Manager", "Index", "LibraryManager")</li>
                    <li>@Html.ActionLink("MPAA Ratings", "Index", "MPAARatings")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Jeremy, Richard, and Darin</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>